---
title: "BE601 - DATA ANALYTICS I"
subtitle: "Seminar 1"
author: "Uyen Vu"
date: "29/08/2022"
output: word_document
monofont: 'consolas'
---

#E1

```{r}
stock <- c(0.04,0.143,0.19,-0.147,-0.265,0.361,0.238)
bill <- c(0.065,0.044,0.038,0.069,0.08,0.058,0.046)
mean_stock <- mean(stock)*100
mean_bill = mean(bill)*100
sd_stock <- sd(stock)*100
sd_bill <- sd(bill)*100
mean_stock
mean_bill
sd_stock
sd_bill
coeff_sd_stock <- sd_stock/mean_stock
coeff_sd_bill <- sd_bill/mean_bill
coeff_sd_stock
coeff_sd_bill
```

#E2
```{r}
a <- c(1,2,3,4,5,6,7,8)
b <- c(1,1,1,1,8,8,8,8)
c <- c(1,1,4,4,5,5,8,8)
d <- c(-6,-3,0,3,6,9,12,15)
df <- data.frame(a = c(1,2,3,4,5,6,7,8),
                 b = c(1,1,1,1,8,8,8,8),
                 c = c(1,1,4,4,5,5,8,8),
                 d = c(-6,-3,0,3,6,9,12,15))
sapply(df, var)
```

#E3

#E4 2.52 Newbold

```{r}
mean <- 686
sd <- 66
k1_5 <- 100*(1-1/1.5^2)
k2 <- 100*(1-1/2^2)
k2_5 <- 100*(1-1/2.5^2)
k3 <- 100*(1-1/3^2)
est <- c(k1_5,k2,k2_5,k3)
est
interval_min <- mean - 2*sd
interval_max <- mean + 2*sd
interval_min
interval_max
```

#E5

```{r}
s1 <- c(84,80,72,72,76,77,75,69,72,62,78,71,70,76,66,77,63,72,68,70)
s2 <- c(70,73,77,76,74,70,67,61,70,70,75,66,75,76,71,67,67,67,70,78,73,66,65,79,66,71,78,72,82,67)
fivenum(s1)
fivenum(s2)
boxplot(s1,s2,
        main = "Weight of persons of age 75 by 2 datasets",
        ylab = "Age",
        at = c(1,2),
        names = c("Dataset 1", "Dataset 2")
        )
```

